#注册中心服务ID
spring:
  application:
    name: register-center-server

#端口号
server:
  port: 10019

#注册中心配置
eureka:
  client:
    # registerWithEureka ：表示是否将自己注册到Eureka Server，默认为true。
    # 由于当前这个应用就是Eureka Server，故而设为false
    register-with-eureka: false
    # fetchRegistry ：表示是否从Eureka Server获取注册信息，默认为true。因为这是一个单点的Eureka Server，
    # 不需要同步其他的Eureka Server节点的数据，故而设为false。
    fetch-registry: false
    # serviceUrl.defaultZone ：设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
    serviceUrl:
      defaultZone: http://localhost:10019/eureka/
